spring.application.name=Edriver

spring.datasource.url=jdbc:postgresql://localhost:5432/edriver_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.sql.init.mode=never

# =======================
# JWT Configuration
# =======================
jwt.secret=YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGY=
jwt.expiration.ms=3600000
jwt.refresh.expiration.ms=86400000

# =======================
# AI Configuration
# =======================
spring.ai.openai.api-key=${OPENAI_API_KEY:AIzaSyBLwRgW-l7_h-W6yJxjtVK8VqQFOWxfaiI}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.options.model=gemini-2.5-flash
spring.ai.openai.embedding.options.model=text-embedding-004

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thantrongan93@gmail.com
spring.mail.password=cfjp artm oprk avco
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# =======================
# Frontend URLs
# =======================
frontend.url.base=http://localhost:5173
frontend.url.dealer.verification=http://localhost:8080/api/auth/verify-dealer
frontend.url.email.verification=http://localhost:8080/api/auth/verify
#frontend.url.email.verification=http://localhost:3000/verify

# =======================
# File Upload
# =======================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB