spring.application.name=Edriver

spring.datasource.url=jdbc:postgresql://localhost:5432/edriver_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.sql.init.mode=never

# JWT (1 gi?)
security.jwt.secret=G9m!P#7dY&x@u2$WzQvB1eR^kL*Fj0hO!sD3nT8pM#lV6bZqR^yC&fG@wX1jL4
security.jwt.expiration-ms=3600000
